### ISSUE TITLE
Missing key

### ISSUE THREAD

**Issue by JunhaoSu0** [jaepoong/PosterLlama#10]
The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. 
The tokenizer class you load from this checkpoint is 'CodeLlamaTokenizer'. 
The class this function is called from is 'LlamaTokenizer'.
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████| 2/2 [00:09<00:00,  4.55s/it]
trainable params: 33,554,432 || all params: 6,772,101,120 || trainable%: 0.4955
Do not use Q-Former here.
Vit_model dino_v2
Load 1 training prompts
Prompt Example 
['[INST] <Img><ImageHere></Img> [/INST] ']
Traceback (most recent call last):
  File "PosterLlama-main/demo.py", line 16, in <module>
    model.load_state_dict(torch.load(base_model,map_location="cpu"))
  File "venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 2189, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for MiniGPT4:
        Missing key(s) in state_dict: "llama_model.base_model.model.model.layers.0.self_attn.q_proj.base_layer.weight", "llama_model.base_model.model.model.layers.0.self_attn.v_proj.base_layer.weight", "llama_model.base_model.model.model.layers.1.self_attn.q_proj.base_layer.weight", "llama_model.base_model.model.model.layers.1.self_attn.v_proj.base_layer.weight", "llama_model.base_model.model.model.layers.2.self_attn.q_proj.base_layer.weight", "llama_model.base_model.model.model.layers.2.self_attn.v_proj.base_layer.weight", "llama_model.base_model.model.model.layers.3.self_attn.q_proj.base_layer.weight", "llama_model.base_model.model.model.layers.3.self_attn.v_proj.base_layer.weight", "llama_model.base_model.model.model.layers.4.self_attn.q_proj.base_layer.weight", "llama_model.base_model.model.model.layers.4.self_attn.v_proj.base_layer.weight", "llama_model.base_model.model.model.layers.5.self_attn.q_proj.base_layer.weight", "llama_model.base_model.model.model.layers.5.self_attn.v_proj.base_layer.weight", "llama_model.base_model.model.model.layers.6.self_attn.q_proj.base_layer.weight", "llama_model.base_model.model.model.layers.6.self_attn.v_proj.base_layer.weight", "llama_model.base_model.model.model.layers.7.self_attn.q_proj.base_layer.weight", "llama_model.base_model.model.model.layers.7.self_attn.v_proj.base_layer.weight", "llama_model.base_model.model.model.layers.8.self_attn.q_proj.base_layer.weight", "llama_model.base_model.model.model.layers.8.self_attn.v_proj.base_layer.weight", "llama_model.base_model.model.model.layers.9.self_attn.q_proj.base_layer.weight", "llama_model.base_model.model.model.layers.9.self_attn.v_proj.base_layer.weight", "llama_model.base_model.model.model.layers.10.self_attn.q_proj.base_layer.weight", "llama_model.base_model.model.model.layers.10.self_attn.v_proj.base_layer.weight", "llama_model.base_model.model.model.layers.11.self_attn.q_proj.base_layer.weight", "llama_model.base_model.model.model.layers.11.self_attn.v_proj.base_layer.weight", "llama_model.base_model.model.model.layers.12.self_attn.q_proj.base_layer.weight", "llama_model.base_model.model.model.layers.12.self_attn.v_proj.base_layer.weight", "llama_model.base_model.model.model.layers.13.self_attn.q_proj.base_layer.weight", "llama_model.base_model.model.model.layers.13.self_attn.v_proj.base_layer.weight", "llama_model.base_model.model.model.layers.14.self_attn.q_proj.base_layer.weight", "llama_model.base_model.model.model.layers.14.self_attn.v_proj.base_layer.weight", "llama_model.base_model.model.model.layers.15.self_attn.q_proj.base_layer.weight", "llama_model.base_model.model.model.layers.15.self_attn.v_proj.base_layer.weight", "llama_model.base_model.model.model.layers.16.self_attn.q_proj.base_layer.weight", "llama_model.base_model.model.model.layers.16.self_attn.v_proj.base_layer.weight", "llama_model.base_model.model.model.layers.17.self_attn.q_proj.base_layer.weight", "llama_model.base_model.model.model.layers.17.self_attn.v_proj.base_layer.weight", "llama_model.base_model.model.model.layers.18.self_attn.q_proj.base_layer.weight", "llama_model.base_model.model.model.layers.18.self_attn.v_proj.base_layer.weight", "llama_model.base_model.model.model.layers.19.self_attn.q_proj.base_layer.weight", "llama_model.base_model.model.model.layers.19.self_attn.v_proj.base_layer.weight", "llama_model.base_model.model.model.layers.20.self_attn.q_proj.base_layer.weight", "llama_model.base_model.model.model.layers.20.self_attn.v_proj.base_layer.weight", "llama_model.base_model.model.model.layers.21.self_attn.q_proj.base_layer.weight", "llama_model.base_model.model.model.layers.21.self_attn.v_proj.base_layer.weight", "llama_model.base_model.model.model.layers.22.self_attn.q_proj.base_layer.weight", "llama_model.base_model.model.model.layers.22.self_attn.v_proj.base_layer.weight", "llama_model.base_model.model.model.layers.23.self_attn.q_proj.base_layer.weight", "llama_model.base_model.model.model.layers.23.self_attn.v_proj.base_layer.weight", "llama_model.base_model.model.model.layers.24.self_attn.q_proj.base_layer.weight", "llama_model.base_model.model.model.layers.24.self_attn.v_proj.base_layer.weight", "llama_model.base_model.model.model.layers.25.self_attn.q_proj.base_layer.weight", "llama_model.base_model.model.model.layers.25.self_attn.v_proj.base_layer.weight", "llama_model.base_model.model.model.layers.26.self_attn.q_proj.base_layer.weight", "llama_model.base_model.model.model.layers.26.self_attn.v_proj.base_layer.weight", "llama_model.base_model.model.model.layers.27.self_attn.q_proj.base_layer.weight", "llama_model.base_model.model.model.layers.27.self_attn.v_proj.base_layer.weight", "llama_model.base_model.model.model.layers.28.self_attn.q_proj.base_layer.weight", "llama_model.base_model.model.model.layers.28.self_attn.v_proj.base_layer.weight", "llama_model.base_model.model.model.layers.29.self_attn.q_proj.base_layer.weight", "llama_model.base_model.model.model.layers.29.self_attn.v_proj.base_layer.weight", "llama_model.base_model.model.model.layers.30.self_attn.q_proj.base_layer.weight", "llama_model.base_model.model.model.layers.30.self_attn.v_proj.base_layer.weight", "llama_model.base_model.model.model.layers.31.self_attn.q_proj.base_layer.weight", "llama_model.base_model.model.model.layers.31.self_attn.v_proj.base_layer.weight". 
        Unexpected key(s) in state_dict: "llama_model.base_model.model.model.layers.0.self_attn.q_proj.weight", "llama_model.base_model.model.model.layers.0.self_attn.v_proj.weight", "llama_model.base_model.model.model.layers.1.self_attn.q_proj.weight", "llama_model.base_model.model.model.layers.1.self_attn.v_proj.weight", "llama_model.base_model.model.model.layers.2.self_attn.q_proj.weight", "llama_model.base_model.model.model.layers.2.self_attn.v_proj.weight", "llama_model.base_model.model.model.layers.3.self_attn.q_proj.weight", "llama_model.base_model.model.model.layers.3.self_attn.v_proj.weight", "llama_model.base_model.model.model.layers.4.self_attn.q_proj.weight", "llama_model.base_model.model.model.layers.4.self_attn.v_proj.weight", "llama_model.base_model.model.model.layers.5.self_attn.q_proj.weight", "llama_model.base_model.model.model.layers.5.self_attn.v_proj.weight", "llama_model.base_model.model.model.layers.6.self_attn.q_proj.weight", "llama_model.base_model.model.model.layers.6.self_attn.v_proj.weight", "llama_model.base_model.model.model.layers.7.self_attn.q_proj.weight", "llama_model.base_model.model.model.layers.7.self_attn.v_proj.weight", "llama_model.base_model.model.model.layers.8.self_attn.q_proj.weight", "llama_model.base_model.model.model.layers.8.self_attn.v_proj.weight", "llama_model.base_model.model.model.layers.9.self_attn.q_proj.weight", "llama_model.base_model.model.model.layers.9.self_attn.v_proj.weight", "llama_model.base_model.model.model.layers.10.self_attn.q_proj.weight", "llama_model.base_model.model.model.layers.10.self_attn.v_proj.weight", "llama_model.base_model.model.model.layers.11.self_attn.q_proj.weight", "llama_model.base_model.model.model.layers.11.self_attn.v_proj.weight", "llama_model.base_model.model.model.layers.12.self_attn.q_proj.weight", "llama_model.base_model.model.model.layers.12.self_attn.v_proj.weight", "llama_model.base_model.model.model.layers.13.self_attn.q_proj.weight", "llama_model.base_model.model.model.layers.13.self_attn.v_proj.weight", "llama_model.base_model.model.model.layers.14.self_attn.q_proj.weight", "llama_model.base_model.model.model.layers.14.self_attn.v_proj.weight", "llama_model.base_model.model.model.layers.15.self_attn.q_proj.weight", "llama_model.base_model.model.model.layers.15.self_attn.v_proj.weight", "llama_model.base_model.model.model.layers.16.self_attn.q_proj.weight", "llama_model.base_model.model.model.layers.16.self_attn.v_proj.weight", "llama_model.base_model.model.model.layers.17.self_attn.q_proj.weight", "llama_model.base_model.model.model.layers.17.self_attn.v_proj.weight", "llama_model.base_model.model.model.layers.18.self_attn.q_proj.weight", "llama_model.base_model.model.model.layers.18.self_attn.v_proj.weight", "llama_model.base_model.model.model.layers.19.self_attn.q_proj.weight", "llama_model.base_model.model.model.layers.19.self_attn.v_proj.weight", "llama_model.base_model.model.model.layers.20.self_attn.q_proj.weight", "llama_model.base_model.model.model.layers.20.self_attn.v_proj.weight", "llama_model.base_model.model.model.layers.21.self_attn.q_proj.weight", "llama_model.base_model.model.model.layers.21.self_attn.v_proj.weight", "llama_model.base_model.model.model.layers.22.self_attn.q_proj.weight", "llama_model.base_model.model.model.layers.22.self_attn.v_proj.weight", "llama_model.base_model.model.model.layers.23.self_attn.q_proj.weight", "llama_model.base_model.model.model.layers.23.self_attn.v_proj.weight", "llama_model.base_model.model.model.layers.24.self_attn.q_proj.weight", "llama_model.base_model.model.model.layers.24.self_attn.v_proj.weight", "llama_model.base_model.model.model.layers.25.self_attn.q_proj.weight", "llama_model.base_model.model.model.layers.25.self_attn.v_proj.weight", "llama_model.base_model.model.model.layers.26.self_attn.q_proj.weight", "llama_model.base_model.model.model.layers.26.self_attn.v_proj.weight", "llama_model.base_model.model.model.layers.27.self_attn.q_proj.weight", "llama_model.base_model.model.model.layers.27.self_attn.v_proj.weight", "llama_model.base_model.model.model.layers.28.self_attn.q_proj.weight", "llama_model.base_model.model.model.layers.28.self_attn.v_proj.weight", "llama_model.base_model.model.model.layers.29.self_attn.q_proj.weight", "llama_model.base_model.model.model.layers.29.self_attn.v_proj.weight", "llama_model.base_model.model.model.layers.30.self_attn.q_proj.weight", "llama_model.base_model.model.model.layers.30.self_attn.v_proj.weight", "llama_model.base_model.model.model.layers.31.self_attn.q_proj.weight", "llama_model.base_model.model.model.layers.31.self_attn.v_proj.weight".

**Comment by tindt-obello** [comment]
use this function to load model instead:
Add to `minigpt4.py`
def load_checkpoint(self, checkpoint_path, map_location="cpu"):
        """
        Load checkpoint with automatic key mapping to handle different model structures.
        This method handles the case where the checkpoint was saved with a different structure
        than the current model (e.g., with/without LoRA).
        """
        checkpoint = torch.load(checkpoint_path, map_location=map_location)
        
        # Handle different checkpoint formats
        if "model" in checkpoint:
            state_dict = checkpoint["model"]
        else:
            state_dict = checkpoint
        
        # Map state_dict keys to match current model structure
        state_dict = self._map_state_dict_keys(state_dict)
        
        # Load with strict=False to handle missing keys gracefully
        msg = self.load_state_dict(state_dict, strict=False)
        
        print(f"Loaded checkpoint from {checkpoint_path}")
        if msg.missing_keys:
            print(f"Missing keys: {len(msg.missing_keys)} keys")
        if msg.unexpected_keys:
            print(f"Unexpected keys: {len(msg.unexpected_keys)} keys")
        
        return msg

Use this function call in `demo.ipynb`:
model.load_checkpoint(base_model, map_location="cpu")
